### DISCUSSION TITLE
operator deployment

### DISCUSSION THREAD

**Discussion by doronl** [PayU/redis-operator#136] [General] [answered]
can I find the operator image in a public registry someware? in the example helm it looks like a local image:

```
 containers:
  - name: manager
    image: redis-operator-docker:local
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 256Mi
```
