### DISCUSSION TITLE
helm chart failed installation with values file

### DISCUSSION THREAD

**Discussion by doronl** [PayU/redis-operator#137] [General] [answered]
Hi, I tried using the following values file:

```
global:
  rbac:
    create: true

redisOperator:
  enabled: true
  namespace: redis2
  managerReplicas: 1 # Number of manger pods the Deployment will create
  configFile: "configfiles/operator.conf"
  labels:
    control-plane: "controller-manager"
    redis-operator: "redis-operator"
  serviceAccount:
  #   create: true
    name: "redis-operator-manager"
  imagePullSecrets:
  - name: regcred
  terminationGracePeriodSeconds: 10

  containers:
  - name: manager
    image: doronl/redis-operator:latest
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 256Mi
    ports:
    - containerPort: 8080
      name: query
    env:
    - name: REDIS_USERNAME
      value: "admin"
    - name: REDISCLI_AUTH
      value: "adminpass"
    - name: CLUSTER_VIEW_FILE
      value: "cluster_data"
    - name: CLUSTER_STATE_FILE
      value: "cluster_state"
    command:
    - "./manager"
    args:
    - "-namespace=redis2"
    - "-metrics-addr=0.0.0.0:9808"
    - "-enable-leader-election=true"
    volumeMounts:
    - name: operator-configuration
      mountPath: "/usr/local/etc/"
  volumes:
  - name: operator-configuration
    configMap:
      name: redis-operator-config

redisCluster:
  enabled: true
  name: dev-rdc
  namespace: redis2
  leaderCount: 3
  leaderFollowersCount: 1
  enableDefaultAffinity: true
  podLabelSelector:
    app: redis-cluster-pod
  redisConfigFile: "configfiles/redis.conf"
  redisACLConfigFile: "configfiles/users.acl"

  redisPodSpec:
    imagePullSecrets:
    - name: regcred

    initContainers: {}

    containers:
    - name: redis-container
      image: quay.io/opstree/redis:v6.2.5
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 1
          memory: 2500Mi
        requests:
          cpu: 1
          memory: 50Mi
      env:
      - name: PORT
        value: "6379"
      - name: CONF_PATH
        value: "/usr/local/etc/redis/redis.conf"
      ports:
      - containerPort: 6379
      volumeMounts:
      - name: redis-configuration
        mountPath: "/usr/local/etc/redis"
      - name: redis-users
        mountPath: "/usr/local/etc/redis/acl"

    - name: redis-metric-exporter
      image: quay.io/opstree/redis-exporter:1.0
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 9121

    volumes:
    - name: redis-configuration
      configMap:
        name: dev-rdc-redisconfig
    - name: redis-users
      configMap:
        name: dev-rdc-users-acl
    - name: host-sys
      hostPath:
        path: "/sys"

    affinity:
      zoneTopologyKey: "topology.kubernetes.io/zone"

    nodeSelector:
      role: redis-memdb-agents
```

I used this command to try installing on EKS:
 **helm install redis-poc ./redis-helm -n redis2**

Got following error:

_E0707 12:03:06.162690  103515 request.go:1085] Unexpected error when reading response body: net/http: request canceled (Client.Timeout or context cancellation while reading body)
W0707 12:03:06.162717  103515 transport.go:288] Unable to cancel request for *exec.roundTripper
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unexpected error when reading response body. Please retry. Original error: net/http: request canceled (Client.Timeout or context cancellation while reading body)_

Any idea?

**Comment by doronl** [comment]
OK, had some issue with other Redis Opeartor, after uninstalling it and its CRD (had a RedisCluster CRD as well...) I am getting this error:


_Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(RedisCluster.spec.redisPodSpec.affinity): unknown field "zoneTopologyKey" in com.payu.db.v1.RedisCluster.spec.redisPodSpec.affinity, ValidationError(RedisCluster.spec.redisPodSpec.initContainers): invalid type for com.payu.db.v1.RedisCluster.spec.redisPodSpec.initContainers: got "map", expected "array"]_

I took the zoneTopologyKey from the [docs](https://github.com/PayU/redis-operator/wiki/Configuration#configuration-example)

**Reply by voltbit** [reply]
Hi, I think the docs are a bit old, try the example manifest in here:

https://github.com/PayU/redis-operator/tree/main/config/samples

To see what fields are supported by the redis cluster resource check the CRD definition or look at the definition here:

https://github.com/PayU/redis-operator/blob/main/api/v1/rediscluster_types.go

Also check this section of the README (if you didnt already):

https://github.com/PayU/redis-operator#deploy-via-helm

**Reply by doronl** [reply]
Thanks, I am working with the section in the readme about trying to install all in helm in the same namespace, below values.yaml file passes installation but opeartor pod **can't run** because of below errors, seems to be an issue with some configMap (my latest helm values.yaml below)

errors:

_MountVolume.SetUp failed for volume "operator-configuration" : configmap "redis-operator-config" not found

Unable to attach or mount volumes: unmounted volumes=[operator-configuration], unattached volumes=[operator-configuration kube-api-access-fhtww]: timed out waiting for the condition

Unable to attach or mount volumes: unmounted volumes=[operator-configuration], unattached volumes=[kube-api-access-fhtww operator-configuration]: timed out waiting for the condition_


values.yaml:

```
global:
  rbac:
    create: true

redisOperator:
  enabled: true
  namespace: redis2
  managerReplicas: 1 # Number of manger pods the Deployment will create
  configFile: "configfiles/operator.conf"
  labels:
    control-plane: "controller-manager"
    redis-operator: "redis-operator"
  serviceAccount:
  #   create: true
    name: "redis-operator-manager"
  imagePullSecrets:
  - name: regcred
  terminationGracePeriodSeconds: 10

  nodeSelector:
    role: operator-agents

  containers:
  - name: manager
    image: doronl/redis-operator:latest
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 256Mi
    ports:
    - containerPort: 8080
      name: query
    env:
    - name: REDIS_USERNAME
      value: "admin"
    - name: REDISCLI_AUTH
      value: "adminpass"
    - name: CLUSTER_VIEW_FILE
      value: "cluster_data"
    - name: CLUSTER_STATE_FILE
      value: "cluster_state"
    command:
    - "./manager"
    args:
    - "-namespace=redis2"
    - "-metrics-addr=0.0.0.0:9808"
    - "-enable-leader-election=true"
    volumeMounts:
    - name: operator-configuration
      mountPath: "/usr/local/etc/"
  volumes:
  - name: operator-configuration
    configMap:
      name: redis-operator-config

redisCluster:
  enabled: true
  name: dev-rdc
  namespace: redis2
  leaderCount: 3
  leaderFollowersCount: 1
  enableDefaultAffinity: true
  podLabelSelector:
    app: redis-cluster-pod
  redisConfigFile: "configfiles/redis.conf"
  redisACLConfigFile: "configfiles/users.acl"

  redisPodSpec:
    imagePullSecrets:
    - name: regcred

    containers:
    - name: redis-container
      image: quay.io/opstree/redis:v6.2.5
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 1
          memory: 2500Mi
        requests:
          cpu: 1
          memory: 50Mi
      env:
      - name: PORT
        value: "6379"
      - name: CONF_PATH
        value: "/usr/local/etc/redis/redis.conf"
      ports:
      - containerPort: 6379
      `volumeMounts`:
      - name: redis-configuration
        mountPath: "/usr/local/etc/redis"
      - name: redis-users
        mountPath: "/usr/local/etc/redis/acl"

    - name: redis-metric-exporter
      image: quay.io/opstree/redis-exporter:1.0
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 9121

    volumes:
    - name: redis-configuration
      configMap:
        name: dev-rdc-redisconfig
    - name: redis-users
      configMap:
        name: dev-rdc-users-acl
    - name: host-sys
      hostPath:
        path: "/sys"

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: role
                  operator: In
                  values:
                    - redis-memdb-agents
            topologyKey: topology.kubernetes.io/zone

    nodeSelector:
      role: redis-memdb-agents
```
