### ISSUE TITLE
Enable work with istio service mesh

### ISSUE THREAD

**Issue by kobiCohen** [PayU/redis-operator#154]
Whenever i try to add a redis cluster to service mesh the operator is deleting the pods, probably due to a connectivity issue.
I see that it is supported in a way with redis cluster, in the official operator: https://github.com/bitnami/charts/issues/4713
it requires some config change in replica.conf file
Which was done like the following: 
(documentation for the official redis operator)
```
slave:
  extraEnvVars:
  - name: "POD_IP"
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
   preExecCmds:  | 
     echo "" >> /opt/bitnami/redis/etc/replica.conf
     echo "replica-announce-ip $POD_IP" >> /opt/bitnami/redis/etc/replica.conf

```
I want to do something similar using this operator.
I have few questions.
1. Was this usecase ever tested or tried? 
2. which path should i use for the replica conf? /usr/local/etc/redis/? if so, this fs is read only, i didn't manage to enable write to it via the cluster config, where can i  change it?
